# Generated by Django 4.2.11 on 2024-03-05 13:44

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('reservation_name', models.CharField(max_length=100)),
                ('groups', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=30), size=None)),
                ('spaces_per_group', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=10), size=None)),
                ('recurring_event', models.BooleanField()),
                ('start_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_date', models.DateField()),
                ('end_time', models.TimeField()),
                ('venue_name', models.CharField(max_length=100)),
                ('venue_address', models.CharField(max_length=1000)),
                ('venue_country', models.CharField(max_length=100)),
                ('online_event', models.BooleanField()),
                ('description', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='ReservationBooking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('customer_name', models.CharField()),
                ('email', models.EmailField(max_length=254)),
                ('alpha_numeric', models.CharField()),
                ('QR_code', models.CharField()),
                ('start_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_date', models.DateField()),
                ('end_time', models.TimeField()),
                ('event_type', models.CharField()),
                ('reservation', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='reservation.reservation')),
            ],
        ),
    ]
